//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAConpay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int Buy1 { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<System.DateTime> BuyTime { get; set; }
        public Nullable<int> BuyNum { get; set; }
        public string BuyDetails { get; set; }
        public string BuyCategory { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
