//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAConpay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collect
    {
        public int CollectID { get; set; }
        public Nullable<decimal> CollectMoney { get; set; }
        public string CollectDetai { get; set; }
        public Nullable<System.DateTime> CollectTime { get; set; }
        public string CollectPerson { get; set; }
        public string CollectPhone { get; set; }
    }
}
