//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAConpay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int PayID { get; set; }
        public Nullable<decimal> PaytMoney { get; set; }
        public string PayDetai { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public string PayName { get; set; }
        public string PayReason { get; set; }
    }
}
