//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAConpay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int SellID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<System.DateTime> SellTime { get; set; }
        public Nullable<int> SellNum { get; set; }
        public string SellDetails { get; set; }
        public string SellCategory { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
