//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAConpay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.Sendpeople = new HashSet<Sendpeople>();
        }
    
        public int SiteId { get; set; }
        public string SiteName { get; set; }
        public string SitePerson { get; set; }
        public string sitePhone { get; set; }
        public string SiteAddress { get; set; }
        public string Site__Category { get; set; }
        public string SiteDeta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sendpeople> Sendpeople { get; set; }
    }
}
